// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.4.16 <0.9.0;

contract C {
    uint public data = 32;
    function x() public returns (uint) {
        data = 3; // internal access
        return this.data(); // external access
    }
}

contract Caller {
    C c = new C();
    function f() public view returns (uint) {
        return c.data();
    }
}


contract arrayExample {
    // public state variable
    uint[] public myArray = [1,2,3,4,5,6];

    // Getter function generated by the compiler
    
    function myArrayCompiler(uint i) public view returns (uint) {
        return myArray[i];
    }
    

    // function that returns entire array
    function getArray() public view returns (uint[] memory) {
        return myArray;
    }
}
